import Head from "next/head"
import NavBar from "../../components/navBar";
import AddContainer from "../../components/AddLink";


function content() {
  return (
    <div>
      <Head>
        <title>FordaStore</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/main-logo.png' />
      </Head>
      <NavBar />
      <main>
        <AddContainer/>
      </main>

    </div>
  )
}

export default content;