import { Head } from 'next/document';
import { ListOfLink } from '../../components/ListOfLink';
import NavBar from '../../components/navBar';

export default function content() {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main-logo.png" />
      </Head>
      <NavBar />
      <main>
        <ListOfLink />
      </main>
    </div>
  );
}
