import Head from "next/head"
import NavBar from "../components/navBar"
import ListOfLink from "../components/listOfContainer"

function Content() {
  return (
    <div className='container-fluid'>
      
      <Head>
        <title>FordaStore</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/main-logo.png' />
      </Head>

      <NavBar />

      <main>
        <ListOfLink/>
      </main>
      
    </div>
  )
}

export default Content;