import Head from 'next/head';
import router from 'next/router';
import { useEffect, useState } from 'react';
import ContainerListTable from '../components/container/ContainerListTable';
import LoadingSpinner from '../components/loading/LoadingSpinner';
import NavBar from '../components/navBar';
import { storeInteractor } from '../lib/localStorage/storeInteractor';

const Home = () => {
  // loading state
  const [showSpinner, setShowSpinner] = useState<boolean>(false);
  const [authProps, setAuthProps] = useState<{ uid: string; token: string }>({
    uid: '',
    token: '',
  });

  useEffect(() => {
    if (storeInteractor.checkToken) {
      console.log('has token: ' + storeInteractor.checkToken);
      setShowSpinner(false);
    } else {
      setShowSpinner(true);
      router.push('/login');
    }
  }, []);

  if (showSpinner) return <LoadingSpinner />;

  return (
    <div>
      <Head>
        <title>FordaStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main-logo.png" />
      </Head>

      <NavBar />

      <ContainerListTable props={authProps} />
    </div>
  );
};

export default Home;
