import Head from 'next/head'

import SideBar from '../components/SideBar'
import EnvironmentalHazard from './environmentalHazard'
import DashboardListTable from '../components/DashboardListTable'

export default function Home() {
  return (
    <div className="flex">
      <Head>
        <title>REEMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className="w-1/6 h-screen bg-gray-200">
        <SideBar />
      </div>

      <div className="w-3/4 h-screen bg-cover bg-center"
        style={{
          backgroundImage: `url('/main-bg.jpg')`,
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          width: "100%"
        }}>

        <div className="grid grid-cols-2 mt-20 ml-80">
          <div className="card rounded-xl w-96 mb-8">
            <div className="card-body"
              style={{
                backgroundImage: `url('/energyConsumption.jpg')`,
                backgroundRepeat: "no-repeat",
                backgroundSize: "cover",
              }}>
              <h2 className="text-lg text-left mt-8 text-right"> Total Energy Consumed: </h2>
              <h2 className="text-2xl text-left ml-48 mb-12"> 250 kw/hr </h2>
            </div>
          </div>

          <div className="card rounded-xl w-96 mb-8" >
            <div className="card-body"
              style={{
                backgroundImage: `url('/expense.jpg')`,
                backgroundRepeat: "no-repeat",
                backgroundSize: "cover",
              }}>
              <h2 className="text-xl text-center ml-40 mt-12"> Total Expenses: </h2>
              <h2 className="text-2xl text-center ml-40"> 20,000 </h2>
            </div>
          </div>

          <div className="card rounded-xl w-96 mb-8">
            <div className="card-body"
              style={{
                backgroundImage: `url('/tenant.jpg')`,
                backgroundRepeat: "no-repeat",
                backgroundSize: "cover",
              }}>
              <h2 className="text-2xl text-center ml-52 mt-6"> Total Tenant: </h2>
              <h2 className="text-3xl text-center ml-52 mb-16"> 545 </h2>
            </div>
          </div>

          <div className="card rounded-xl w-96 mb-8">
            <div className="card-body"
              style={{
                backgroundImage: `url('/property.jpg')`,
                backgroundRepeat: "no-repeat",
                backgroundSize: "cover",
              }}>
              <h2 className="text-2xl text-center ml-32 mt-16"> Total Property: </h2>
              <h2 className="text-2xl text-center ml-32 mb-16"> 50 </h2>
            </div>
          </div>
        </div>

        <div className="card rounded-xl ml-80 mr-64 mb-20">
          <div className="card-body"
          style={{
            backgroundImage: `url('/nav-bg.png')`,
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
          }}>
            <DashboardListTable />
          </div>
        </div>
      </div>
    </div>
  )
}
