import Head from 'next/head';
import Link from 'next/dist/client/link';
import NavBar from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title> REEMS </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main-logo.png" />
      </Head>

      <NavBar />

      <div className="container-fluid"
        style={{
          backgroundImage: "url('/bg.jpg')",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          backgroundPosition: "center",
          paddingTop: "4rem",
          paddingBottom: "4rem"
        }}
      >
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-20 mx-6 md:mx-40 my-10">
          <Link href="/environmentalHazard" className="no-underline">
            <div className="card md:mx-auto rounded-xl"  style={{ width: "28rem"}}>
              <div className="relative">
                <img src="/environmentalHazard.png" className="z-10 mx-auto text-center rounded-xl"
                  style={{ width: "26rem", height: "18rem", marginTop: "-2rem" }} alt="Environmental Hazard" />
                <div className="card-body bg-white z-20 rounded-xl mt-3">
                  <h2 className='text-2xl text-center text-black'>Environmental Hazard Tracker</h2>
                </div>
              </div>
            </div>
          </Link>

          <Link href="/energyConsumption" className="no-underline">
            <div className="card mx-auto rounded-xl"  style={{ width: "28rem"}}>
              <div className="relative">
                <img src="/energyConsumption.png" className="z-10 mx-auto text-center rounded-xl"
                  style={{ width: "26rem", height: "18rem", marginTop: "-2rem" }} alt="Energy Consumption" />
                <div className="card-body bg-white z-20 rounded-xl">
                  <h2 className='text-2xl text-center text-black'>Energy Consumption Tracker</h2>
                </div>
              </div>
            </div>
          </Link>

          <Link href="/expense" className="no-underline">
            <div className="card mx-auto rounded-xl"  style={{ width: "28rem"}}>
              <div className="relative">
                <img src="/expense.png" className="z-10 mx-auto text-center rounded-xl"
                  style={{ width: "26rem", height: "18rem", marginTop: "-2rem" }} alt="Expense" />
                <div className="card-body bg-white z-20 rounded-xl">
                  <h2 className='text-2xl text-center text-black'>Expense Tracker</h2>
                </div>
              </div>
            </div>
          </Link>

          <Link href="/tenantInformation" className="no-underline">
            <div className="card mx-auto rounded-xl"  style={{ width: "28rem"}}>
              <div className="relative">
                <img src="/tenantInformation.png" className="z-10 mx-auto text-center rounded-xl"
                  style={{ width: "26rem", height: "18rem", marginTop: "-2rem" }} alt="Tenant Information" />
                <div className="card-body bg-white z-20 rounded-xl">
                  <h2 className='text-2xl text-center text-black'>Tenant Information Tracker</h2>
                </div>
              </div>
            </div>
          </Link>
        </div>
      </div>

    </div >
  );
};
