import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { FormEvent, useState } from "react";
import { useAuth } from "../context/AuthContext";
import { useRouter } from "next/router";

export default function Login() {
  const router = useRouter()
  const { user, login } = useAuth()
  console.log(user)

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleLogin = async (e: FormEvent) => {
    e.preventDefault()

    try {
      await login(email, password)
      router.push('/home')
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <div className="container-fluid"
      style={{ backgroundImage: "url('/background.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "center" }}
    >
      <Head>
        <title> REEMS </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>

      <div className="row">
        <div className="col-sm-6 col-md-5 m-auto">
          <div className="card mb-52 mt-32" style={{ backgroundColor: "rgba(255, 255, 255, 0.9)" }}>
            <div className="card-body my-32 mx-16 ">
              <Image
                src="/logo.png"
                className="h-32 w-32 border border-transparent rounded-full absolute top-0 end-0"
                alt="logo.png"
                width={200}
                height={200}
                style={{ marginTop: "1rem", marginRight: "1rem" }}
              />
              <div className="d-flex justify-content-center">
                <Image
                  src="/user-icon.png"
                  className="img-thumbnail border border-white w-24 h-24"
                  alt="user-icon.png"
                  width={300}
                  height={300}
                />
              </div>

              <div className="fs-1 d-flex justify-content-center fw-bold">
                Sign in
              </div>

              <form onSubmit={handleLogin}>
                <div className="input-group mt-5 ">
                  <div className="input-group-text bg-white border-secondary border-end-0">
                    <i className="bi bi-envelope"></i>
                  </div>

                  <input
                    className="form-control border-secondary border-start-0"
                    type="text"
                    placeholder="Email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </div>

                <div className="input-group mt-4">

                  <div className="input-group-text bg-white border-secondary border-end-0">
                    <i className="bi bi-lock"></i>
                  </div>

                  <input
                    className="form-control border-secondary border-start-0"
                    type="password"
                    placeholder="Password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                  />
                </div>

                <div>
                  <button
                    type="submit"
                    className="btn btn-success mt-5 w-100 border border-secondary rounded-pill">
                    Login
                  </button>
                </div>

                <div className="text-center mt-2">
                  Not registered?
                  <Link href="/register"> Create an Account </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
