import Head from 'next/head'
import LandingNavBar from '../components/LandingNavbar'

export default function MainPage() {
  return (
    <div>
      <Head>
        <title>REEMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-2.png" />
      </Head>

      <LandingNavBar />

      <div className="container-fluid mx-auto bg-cover bg-center min-h-screen min-w-screen"
        style={{ backgroundImage: "url('/main-bg.jpg')", backgroundColor: "#fff" }}>

        <div className="container-fluid mx-auto flex flex-wrap min-h-screen min-w-screen ">
          <div className="card ml-52 my-auto" style={{ backgroundColor: "rgba(255, 255, 255, 0.5)", boxShadow: "0px 20px 20px rgba(0, 0, 0, 0.5)" }}>
            <div className="card-body my-32 mx-12">

              <div className="text text-7xl mb-28">
                <div style={{ fontFamily: 'cursive' }}> Manage Real Estate</div>
                <div style={{ fontFamily: 'cursive' }}> and Environment </div>
              </div>

              <div className="text text-2xl">
                Reems provides the ease of managing multiple properties
              </div>
              <div className="text text-2xl">
                and keeping track of your surrounding environment.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
