import Head from 'next/head';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/router';
import { UserRequest } from '../lib/user/userRequest';
import Modal from 'react-bootstrap/Modal';
import { registerInteractor } from '../lib/auth/registerInteractor';
import Image from 'next/image';

export default function Register() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const router = useRouter();

  const [show, setShow] = useState(false);
  const closeModal = () => setShow(false);
  const showModal = () => setShow(true);

  const register = async (event: FormEvent) => {
    event.preventDefault();

    if (password !== confirmPassword) {
      return alert('password did not match');
    }

    const isRegistered = await registerInteractor({ password, username });

    if (isRegistered) {
      showModal();

      setUsername('');
      setPassword('');

      setTimeout(() => router.push('/'), 5000);
    } else {
      alert('your weak! ' + username);
    }
  };

  return (
    <div className="container-fluid">
      <Head>
        <title> FordaStore </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main-logo.png" />
      </Head>

      <Image
        src="/logo.png"
        className="img-thumbnail w-25 h-25 border border-white"
        alt="logo.png"
        width={500}
        height={500}
      />

      <div className="row">
        <div className="col-sm-6 col-md-5 m-auto">
          <div className="d-flex justify-content-center">
            <Image
              src="/user-icon.png"
              className="img-thumbnail border border-white w-24 h-24"
              alt="user-icon.png"
              width={300}
              height={300}
            />
          </div>

          <div className="fs-1 d-flex justify-content-center fw-bold">
            Register
          </div>

          <form onSubmit={register}>
            <div>
              <input
                className="form-control mt-5 border border-dark"
                type="text"
                placeholder="Username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </div>

            <div>
              <input
                className="form-control mt-4 border border-dark"
                type="password"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>

            <div>
              <input
                className="form-control mt-4 border border-dark"
                type="password"
                placeholder="Confirm Password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
              />
              <div id="passwordHelpBlock" className="form-text">
                Your password must be 8-20 characters long, contain letters and
                numbers, and must not contain spaces, special characters, or
                emoji.
              </div>
            </div>

            <div>
              <button
                type="submit"
                className="btn btn-info mt-5 w-100 border border-dark"
              >
                Register
              </button>
            </div>
          </form>
        </div>
      </div>
      <Modal show={show} onHide={closeModal}>
        <Modal.Header closeButton>
          <Modal.Title>Registration Successful</Modal.Title>
        </Modal.Header>
      </Modal>
    </div>
  );
}
