import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { useRouter } from "next/router";

export default function Register() {
  const router = useRouter()
  const { user, register } = useAuth()
  console.log(user)

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleRegister = async (e: any) => {
    e.preventDefault()

    try {
      await register(email, password)
      router.push('/login')
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <div className="container-fluid">
      <Head>
        <title> REEMS </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Image
        src="/logo.jpg"
        className="img-thumbnail w-32 h-32 border border-white"
        alt="logo.jpg"
        width={200}
        height={200}
      />

      <div className="row">
        <div className="col-sm-6 col-md-5 m-auto">
          <div className="d-flex justify-content-center">
            <Image
              src="/user-icon.png"
              className="img-thumbnail border border-white w-24 h-24"
              alt="user-icon.png"
              width={300}
              height={300}
            />
          </div>

          <div className="fs-1 d-flex justify-content-center fw-bold">
            Register
          </div>

          <form onSubmit={handleRegister}>
            <div>
              <input
                className="form-control mt-5 border border-dark"
                type="text"
                placeholder="Email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>

            <div>
              <input
                className="form-control mt-4 border border-dark"
                type="password"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>

            <div>
              <button
                type="submit"
                className="btn btn-success mt-5 w-100 border border-dark"
              >
                Register
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
